package vn.aequitas.coreplatform.domain.common;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Transient;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.domain.Persistable;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.UUID;

/**
 * Base type shared by every persisted entity. Mirrors the .NET {@code BaseEntity}:
 * an application-assigned {@code Guid} primary key plus audit / soft-delete columns.
 *
 * <p>The id and audit columns keep their original PascalCase names so the mapping
 * stays compatible with the schema created by the EF Core migrations. GUIDs are
 * stored as {@code char(36)} (the Pomelo/MySQL representation), so the {@link UUID}
 * is bound as its 36-character string form.</p>
 *
 * <p>The primary key is assigned in application code, never generated by the
 * database. For such keys Spring Data cannot infer whether a {@code save()} is an
 * insert or an update from a {@code null} id, so this class implements
 * {@link Persistable}: an entity is "new" until it is first loaded or persisted,
 * which makes {@code JpaRepository.save} issue a plain {@code INSERT} instead of a
 * {@code SELECT}-then-{@code merge}. This preserves the eager-insert semantics of
 * the former hand-rolled repository.</p>
 */
@Getter
@Setter
@MappedSuperclass
public abstract class BaseEntity implements Persistable<UUID> {

    @Id
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "Id", columnDefinition = "char(36)", updatable = false, nullable = false)
    private UUID id = UUID.randomUUID();

    @Column(name = "IsActive")
    private boolean isActive = true;

    @Column(name = "CreatedBy", columnDefinition = "longtext")
    private String createdBy = "";

    @Column(name = "UpdatedBy", columnDefinition = "longtext")
    private String updatedBy = "";

    @Column(name = "CreatedDate", columnDefinition = "datetime(6)")
    private LocalDateTime createdDate = LocalDateTime.now(ZoneOffset.UTC);

    @Column(name = "UpdatedDate", columnDefinition = "datetime(6)")
    private LocalDateTime updatedDate = LocalDateTime.now(ZoneOffset.UTC);

    /** Backs {@link #isNew()}; cleared once the row is loaded from or written to the database. */
    @Transient
    private boolean newEntity = true;

    @Override
    public boolean isNew() {
        return newEntity;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.newEntity = false;
    }
}
